[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
zeroperp = "FF51h2MwJQUNxUAKN8CXJJSNDni5jCNXb2GzAQT1D7jy"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
